import { Injectable, Signal, inject, signal } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import { PrimeNG } from 'primeng/config';

export type Lang = 'bg' | 'ru' | 'en';
const STORAGE_KEY = 'harmonia-lang';

export const PRIMENG_TRANSLATIONS: Record<Lang, object> = {
  bg: {
    firstDayOfWeek: 1,
    dayNames: ['Неделя', 'Понеделник', 'Вторник', 'Сряда', 'Четвъртък', 'Петък', 'Събота'],
    dayNamesShort: ['Нед', 'Пон', 'Вт', 'Ср', 'Чет', 'Пет', 'Съб'],
    dayNamesMin: ['Нд', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
    monthNames: ['Януари', 'Февруари', 'Март', 'Април', 'Май', 'Юни', 'Юли', 'Август', 'Септември', 'Октомври', 'Ноември', 'Декември'],
    monthNamesShort: ['Яну', 'Фев', 'Мар', 'Апр', 'Май', 'Юни', 'Юли', 'Авг', 'Сеп', 'Окт', 'Ное', 'Дек'],
    today: 'Днес',
    clear: 'Изчисти',
    weekHeader: 'Сед',
    dateFormat: 'dd.mm.yy',
    accept: 'Да',
    reject: 'Не',
    choose: 'Избери',
    upload: 'Качи',
    cancel: 'Отказ',
    fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
    aria: {
      trueLabel: 'Вярно',
      falseLabel: 'Невярно',
      nullLabel: 'Не е избрано',
      star: '1 звезда',
      stars: '{0} звезди',
      selectAll: 'Избери всички',
      unselectAll: 'Премахни всички',
      close: 'Затвори',
      previous: 'Предишен',
      next: 'Следващ',
      navigation: 'Навигация',
      scrollTop: 'Нагоре',
      moveTop: 'Премести най-горе',
      moveUp: 'Премести нагоре',
      moveDown: 'Премести надолу',
      moveBottom: 'Премести най-долу',
      moveToTarget: 'Премести към целта',
      moveToSource: 'Премести към източника',
      moveAllToTarget: 'Премести всички към целта',
      moveAllToSource: 'Премести всички към източника',
      pageLabel: 'Страница {page}',
      firstPageLabel: 'Първа страница',
      lastPageLabel: 'Последна страница',
      nextPageLabel: 'Следваща страница',
      previousPageLabel: 'Предишна страница',
      rowsPerPageLabel: 'Редове на страница',
      jumpToPageDropdownLabel: 'Отиди на страница',
      jumpToPageInputLabel: 'Отиди на страница',
      selectRow: 'Избери ред',
      unselectRow: 'Премахни ред',
      expandRow: 'Разшири ред',
      collapseRow: 'Свий ред',
      showFilterMenu: 'Покажи филтри',
      hideFilterMenu: 'Скрий филтри',
      filterOperator: 'Оператор на филтър',
      filterConstraint: 'Ограничение на филтър',
      editRow: 'Редактирай ред',
      saveEdit: 'Запази',
      cancelEdit: 'Отказ',
      listView: 'Изглед на списък',
      gridView: 'Мрежов изглед',
      slide: 'Слайд',
      slideNumber: 'Слайд {slideNumber}',
      zoomImage: 'Увеличи изображение',
      zoomIn: 'Увеличи',
      zoomOut: 'Намали',
      rotateRight: 'Завърти надясно',
      rotateLeft: 'Завърти наляво',
    },
  },
  en: {
    firstDayOfWeek: 0,
    dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    dayNamesShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    today: 'Today',
    clear: 'Clear',
    weekHeader: 'Wk',
    dateFormat: 'mm/dd/yy',
    accept: 'Yes',
    reject: 'No',
    choose: 'Choose',
    upload: 'Upload',
    cancel: 'Cancel',
    fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
    aria: {
      trueLabel: 'True',
      falseLabel: 'False',
      nullLabel: 'Not Selected',
      star: '1 star',
      stars: '{0} stars',
      selectAll: 'Select All',
      unselectAll: 'Unselect All',
      close: 'Close',
      previous: 'Previous',
      next: 'Next',
      navigation: 'Navigation',
      scrollTop: 'Scroll Top',
      moveTop: 'Move Top',
      moveUp: 'Move Up',
      moveDown: 'Move Down',
      moveBottom: 'Move Bottom',
      moveToTarget: 'Move to Target',
      moveToSource: 'Move to Source',
      moveAllToTarget: 'Move All to Target',
      moveAllToSource: 'Move All to Source',
      pageLabel: 'Page {page}',
      firstPageLabel: 'First Page',
      lastPageLabel: 'Last Page',
      nextPageLabel: 'Next Page',
      previousPageLabel: 'Previous Page',
      rowsPerPageLabel: 'Rows per page',
      jumpToPageDropdownLabel: 'Go to page',
      jumpToPageInputLabel: 'Go to page',
      selectRow: 'Select Row',
      unselectRow: 'Unselect Row',
      expandRow: 'Expand Row',
      collapseRow: 'Collapse Row',
      showFilterMenu: 'Show Filter Menu',
      hideFilterMenu: 'Hide Filter Menu',
      filterOperator: 'Filter Operator',
      filterConstraint: 'Filter Constraint',
      editRow: 'Edit Row',
      saveEdit: 'Save Edit',
      cancelEdit: 'Cancel Edit',
      listView: 'List View',
      gridView: 'Grid View',
      slide: 'Slide',
      slideNumber: 'Slide {slideNumber}',
      zoomImage: 'Zoom Image',
      zoomIn: 'Zoom In',
      zoomOut: 'Zoom Out',
      rotateRight: 'Rotate Right',
      rotateLeft: 'Rotate Left',
    },
  },
  ru: {
    firstDayOfWeek: 1,
    dayNames: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
    dayNamesShort: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
    dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
    monthNames: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
    monthNamesShort: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
    today: 'Сегодня',
    clear: 'Очистить',
    weekHeader: 'Нед',
    dateFormat: 'dd.mm.yy',
    accept: 'Да',
    reject: 'Нет',
    choose: 'Выбрать',
    upload: 'Загрузить',
    cancel: 'Отмена',
    fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
    aria: {
      trueLabel: 'Истина',
      falseLabel: 'Ложь',
      nullLabel: 'Не выбрано',
      star: '1 звезда',
      stars: '{0} звезды',
      selectAll: 'Выбрать все',
      unselectAll: 'Снять выбор',
      close: 'Закрыть',
      previous: 'Предыдущий',
      next: 'Следующий',
      navigation: 'Навигация',
      scrollTop: 'Прокрутить вверх',
      moveTop: 'В начало',
      moveUp: 'Вверх',
      moveDown: 'Вниз',
      moveBottom: 'В конец',
      moveToTarget: 'В цель',
      moveToSource: 'В источник',
      moveAllToTarget: 'Всё в цель',
      moveAllToSource: 'Всё в источник',
      pageLabel: 'Страница {page}',
      firstPageLabel: 'Первая страница',
      lastPageLabel: 'Последняя страница',
      nextPageLabel: 'Следующая страница',
      previousPageLabel: 'Предыдущая страница',
      rowsPerPageLabel: 'Строк на странице',
      jumpToPageDropdownLabel: 'Перейти на страницу',
      jumpToPageInputLabel: 'Перейти на страницу',
      selectRow: 'Выбрать строку',
      unselectRow: 'Снять выбор строки',
      expandRow: 'Раскрыть строку',
      collapseRow: 'Свернуть строку',
      showFilterMenu: 'Показать фильтры',
      hideFilterMenu: 'Скрыть фильтры',
      filterOperator: 'Оператор фильтра',
      filterConstraint: 'Условие фильтра',
      editRow: 'Редактировать строку',
      saveEdit: 'Сохранить',
      cancelEdit: 'Отмена',
      listView: 'Список',
      gridView: 'Сетка',
      slide: 'Слайд',
      slideNumber: 'Слайд {slideNumber}',
      zoomImage: 'Увеличить',
      zoomIn: 'Приблизить',
      zoomOut: 'Отдалить',
      rotateRight: 'Повернуть вправо',
      rotateLeft: 'Повернуть влево',
    },
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly translate = inject(TranslateService);
  private readonly primeNG = inject(PrimeNG);
  private readonly _current = signal<Lang>(this.getInitialLang());

  readonly current: Signal<Lang> = this._current.asReadonly();

  init(): void {
    this.translate.setDefaultLang('bg');
    this.applyLang(this._current());
  }

  setLang(lang: Lang): void {
    localStorage.setItem(STORAGE_KEY, lang);
    this._current.set(lang);
    this.applyLang(lang);
  }

  private applyLang(lang: Lang): void {
    this.translate.use(lang);
    this.primeNG.setTranslation(PRIMENG_TRANSLATIONS[lang]);
  }

  private getInitialLang(): Lang {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored === 'bg' || stored === 'ru' || stored === 'en' ? stored : 'bg';
  }
}
